replicas: 1
image: {}
containerPort: 8080
resources: {}
service: {}
ingress:
  enabled: false
podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
#  fsGroup: 1000
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
env: {}

