apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: config-secrets
  namespace: sentinel-mind
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/configsecrets"
        objectType: "secretsmanager"
        objectAlias: "secrets.yaml"
    region: "us-east-1"
    