apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: sentinel-mind
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::442426895473:role/secrets-store-csi-driver-service-account-role
