apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: sentinel-mind
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/chainlit-secrets"
        objectType: "secretsmanager"
        jmesPath:
          #- path: AWS_ACCESS_KEY_ID
          # objectAlias: aws-access-key-id

          - path: AWS_REGION
            objectAlias: aws-region

          #- path: AWS_SECRET_ACCESS_KEY
          # objectAlias: aws-secret-access-key

          - path: CHAINLIT_AUTH_SECRET
            objectAlias: chainlit-auth-secret

          - path: CHROMADB_CLIENT_TYPE
            objectAlias: chromadb-client-type

          - path: CHROMADB_HOST
            objectAlias: chromadb-host

          - path: CHROMADB_PERSISTENT_PATH
            objectAlias: chromadb-persistent-path

          - path: CHROMADB_PORT
            objectAlias: chromadb-port

          - path: GITHUB_PERSONAL_ACCESS_TOKEN
            objectAlias: github-personal-access-token

          - path: GITHUB_USERNAME
            objectAlias: github-username

          - path: GOOGLE_API_KEY
            objectAlias: google-api-key

          - path: INPUT_TOKEN_COST_PER_1000
            objectAlias: input-token-cost-per-1000

          - path: LOG_LEVEL
            objectAlias: log-level

          - path: OAUTH_ENABLED
            objectAlias: oauth-enabled

          - path: OAUTH_KEYCLOAK_BASE_URL
            objectAlias: oauth-keycloak-base-url

          - path: OAUTH_KEYCLOAK_CLIENT_ID
            objectAlias: oauth-keycloak-client-id

          - path: OAUTH_KEYCLOAK_CLIENT_SECRET
            objectAlias: oauth-keycloak-client-secret

          - path: OAUTH_KEYCLOAK_NAME
            objectAlias: oauth-keycloak-name

          - path: OAUTH_KEYCLOAK_REALM
            objectAlias: oauth-keycloak-realm

          - path: OAUTH_KEYCLOAK_REDIRECT_URI
            objectAlias: oauth-keycloak-redirect-uri

          - path: OUTPUT_TOKEN_COST_PER_1000
            objectAlias: output-token-cost-per-1000

          - path: SLACK_BOT_TOKEN
            objectAlias: slack-bot-token

          - path: SLACK_SIGNING_SECRET
            objectAlias: slack-signing-secret

          - path: CLUSTER_NAME
            objectAlias: cluster-name

          - path: ENV
            objectAlias: environment

          - path: LOKI_URL
            objectAlias: loki-url

          - path: LOKI_USERNAME
            objectAlias: loki-username

          - path: LOKI_PASSWORD
            objectAlias: loki-password


    region: "us-east-1"

  secretObjects:
  - secretName: prod-chainlit-secrets
    type: Opaque
    data:
    #- objectName: "aws-access-key-id"
    # key: AWS_ACCESS_KEY_ID

    - objectName: "aws-region"
      key: AWS_REGION

    #- objectName: "aws-secret-access-key"
    # key: AWS_SECRET_ACCESS_KEY

    - objectName: "chainlit-auth-secret"
      key: CHAINLIT_AUTH_SECRET

    - objectName: "chromadb-client-type"
      key: CHROMADB_CLIENT_TYPE

    - objectName: "chromadb-host"
      key: CHROMADB_HOST

    - objectName: "chromadb-persistent-path"
      key: CHROMADB_PERSISTENT_PATH

    - objectName: "chromadb-port"
      key: CHROMADB_PORT

    - objectName: "github-personal-access-token"
      key: GITHUB_PERSONAL_ACCESS_TOKEN

    - objectName: "github-username"
      key: GITHUB_USERNAME

    - objectName: "google-api-key"
      key: GOOGLE_API_KEY

    - objectName: "input-token-cost-per-1000"
      key: INPUT_TOKEN_COST_PER_1000

    - objectName: "log-level"
      key: LOG_LEVEL

    - objectName: "oauth-enabled"
      key: OAUTH_ENABLED

    - objectName: "oauth-keycloak-base-url"
      key: OAUTH_KEYCLOAK_BASE_URL

    - objectName: "oauth-keycloak-client-id"
      key: OAUTH_KEYCLOAK_CLIENT_ID

    - objectName: "oauth-keycloak-client-secret"
      key: OAUTH_KEYCLOAK_CLIENT_SECRET

    - objectName: "oauth-keycloak-name"
      key: OAUTH_KEYCLOAK_NAME

    - objectName: "oauth-keycloak-realm"
      key: OAUTH_KEYCLOAK_REALM

    - objectName: "oauth-keycloak-redirect-uri"
      key: OAUTH_KEYCLOAK_REDIRECT_URI

    - objectName: "output-token-cost-per-1000"
      key: OUTPUT_TOKEN_COST_PER_1000

    - objectName: "slack-bot-token"
      key: SLACK_BOT_TOKEN

    - objectName: "slack-signing-secret"
      key: SLACK_SIGNING_SECRET

    - objectName: "cluster-name"
      key: CLUSTER_NAME

    - objectName: "environment"
      key: ENV

    - objectName: "loki-url"
      key: LOKI_URL

    - objectName: "loki-username"
      key: LOKI_USERNAME

    - objectName: "loki-password"
      key: LOKI_PASSWORD
