secrets:
  - id: gcp-service-account
    paths:
      - "**/.venv/**/site-packages/chainlit/data/storage_clients/gcs.py"
      - "**/site-packages/chainlit/data/storage_clients/gcs.py"

vulnerabilities:
  - id: CVE-2025-62727
    comment: "Temporary ignore;  Will remove after upgrading the version to 0.49.1"
  - id: CVE-2022-33064
    comment: " No fixed version yet"
  - id: CVE-2025-52194
    comment: " No fixed version yet and is affected"
  - id: CVE-2025-6176
    comment: "Latest Vulernability from package Brotli came on oct-31 and is not fixed yet"
  - id: CVE-2025-64439
    comment: "Fixed in  langgraph-checkpoint `3.0`"