apiVersion: v1
kind: ConfigMap
metadata:
  name: chainlit-llm-config
  namespace: sentinel-mind
data:
  config.yaml: |
    llm:
      # bedrock:
      #   max_tokens: 2000
      #   model: "amazon.nova-micro-v1:0"
      #   # model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      #   temperature: 0.0
      agent:
        recursion_limit: 50
    mcp:
      servers:
        default:
          command: "python3"
          args: ["-m", "mcp_server_fetch"]
          transport: "stdio"
        playwright_hl:
          command: "npx"
          args:
            - "@playwright/mcp"
            - "--ignore-https-errors"
            - "--headless"
            - "--browser=chromium"
            - "--no-sandbox"
            # - "--user-data-dir=/tmp/mcp-profile-$(uuidgen)"
            - "--isolated"
          transport: "stdio"
          chainlit_command:
            id: "Browser-HL"
            icon: "globe"
            description: "Search through browser(headless)"
        # playwright:
        #   command: "npx"
        #   args:
        #     - "@playwright/mcp@latest"
        #     - "--ignore-https-errors"
        #     - "--browser=chromium"
        #     - "--no-sandbox"
        #   env:
        #     DISPLAY: ":1"
        #     PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
        #   transport: "stdio"
        #   chainlit_command:
        #     id: "Browser"
        #     icon: "globe"
        #     description: "Search through browser"
        cloudwatch_logs:
          command: "uvx"
          args: ["awslabs.cloudwatch-logs-mcp-server@latest"]
          transport: "stdio"
          chainlit_command:
            id: "Cloudwatch"
            icon: "cloud"
            description: "Search through aws cloudwatch logs"
        cost_explorer:
          command: "uvx"
          args: ["awslabs.cost-explorer-mcp-server@latest"]
          transport: "stdio"
          chainlit_command:
            id: "AWS cost"
            icon: "dollar-sign"
            description: "Analyze AWS costs and usage data through the AWS Cost Explorer API."
        gitlab:
          command: "npx"
          args: ["-y", "@modelcontextprotocol/server-gitlab"]
          transport: "stdio"
          chainlit_command:
            id: "GitLab"
            icon: "gitlab"
            description: "Search through GitLab"
        github:
          type: "streamable_http"
          transport: "streamable_http"
          url: "https://api.githubcopilot.com/mcp"
          chainlit_command:
            id: "GitHub"
            icon: "github"
            description: "Search through GitHub"
        jenkins:
          type: "sse"
          transport: "sse"
          url: "https://app.ustpace.io/visioncheckout/jenkins/mcp-server/sse"
          chainlit_command:
            id: "Jenkins"
            icon: "repeat-2"
            description: "Search through Jenkins"

        grafana:
          type: "streamable_http"
          transport: "streamable_http"
          url: "http://grafana-mcp-service.sentinel-mind.svc.cluster.local:8000/mcp"
          chainlit_command:
            id: "Grafana"
            icon: "bar-chart-2"
            description: "Query Grafana dashboards and data sources"

    chainlit_profiles:
      nova_micro:
        bedrock:
          model: "amazon.nova-micro-v1:0"
          max_tokens: 2000
          temperature: 0.0
        description: "Nova Micro. Model for text related tasks"
        cost:
          input_token_cost: 0.000035
          output_token_cost: 0.00014
      Claude_Sonnet_3.7:
        bedrock:
          model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
          max_tokens: 2000
          temperature: 0.0
        description: "Claude Sonnet 3.7. Model for browser related tasks"
        cost:
          input_token_cost: 0.003
          output_token_cost: 0.015
      nova_pro:
        bedrock:
          model: "amazon.nova-pro-v1:0"
          max_tokens: 2000
          temperature: 0.0
        description: "Nova Pro. Model for text related tasks"
        cost:
          input_token_cost: 0.0008
          output_token_cost: 0.0032
