apiVersion: v1
kind: Service
metadata:
  name: chainlit-app-service
  namespace: sentinel-mind
spec:
  selector:
    app: chainlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
