llm:
  bedrock:
    max_tokens: 2000
    model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    temperature: 0.0
mcp:
  servers:
    fetch:
      command: "npx"
      args: ["@playwright/mcp@latest", "--ignore-https-errors", "--headless"]
    playwright:
      command: "node"
      args: ["playwright-mcp//cli.js"]
      env:
        DISPLAY: ":1"
    cloudwatch_logs_mcp_server:
      command: "uvx"
      args: ["awslabs.cloudwatch-logs-mcp-server@latest"]
    cost_explorer_mcp_server:
      command: "uvx"
      args: ["awslabs.cost-explorer-mcp-server@latest"]
    github:
      command: docker
      args:
        - run
        - -i
        - --rm
        - -e
        - GITHUB_PERSONAL_ACCESS_TOKEN
        - ghcr.io/github/github-mcp-server
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
