llm:
  bedrock:
    max_tokens: 2000
    model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    temperature: 0.0
mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    playwright:
      command: "node"
      args: ["playwright-mcp//cli.js"]
      env:
        DISPLAY: ":1"
