name: Pylint Github Action

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
jobs:
  pylint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Git (if missing)
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" 
      
      - name: Install pylint with apt
        run: sudo apt update && sudo apt install -y pylint
          
      - name: Get Changed Python Files
        id: changed-files
        run: |
          git fetch --no-tags --depth=50  # Ensure enough history for diff
          FILES=$(git diff --name-status origin/main..HEAD -- '*.py' | awk '$1 != "D" {print $2}') 
          if [ -n "$FILES" ]; then
            echo "PY_FILES=$(echo "$FILES" | tr '\n' ' ')" >> "$GITHUB_ENV"
          else
            echo "PY_FILES=" >> $GITHUB_ENV
          fi

      - name: Python Linter
        if: env.PY_FILES != ''
        run: |
          for file in $PY_FILES; do
            echo "Linting $file"
            pylint --rcfile=.pylintrc "$file"
          done

