name: Security and Lint Checks

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'streamlit/**'

jobs:
  trivy-dependency-scan:
    name: Trivy Scan requirements.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy (excluding streamlit/)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'library'
          skip-dirs: 'streamlit'

  lint-flake8:
    name: Flake8 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 (excluding streamlit/)
        run: flake8 . --exclude=streamlit

  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (excluding streamlit/)
        run: bandit -r . --exclude streamlit
