name: SonarQube Nightly Build
# https://sonar.ustpace.com/dashboard?id=sflabs-ai-assistant

on:
  workflow_dispatch: {}    # allow manual trigger
  schedule:
     - cron: "0 4 * * *"   # every day at 4:00 UTC

permissions:
  contents: write

jobs:
  Call-reusable-workflow:
    uses: UST-PACE/gh-actions-shared-library/.github/workflows/reusable_sonar_scan_nightly_job_submit.yaml@main
    with:
      ref: ${{ github.ref }}
      branch: main
      build_options_file_name: build_options.txt
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
