name: Veracode SAST Nightly Build

# # Time being manually triggered.
on:
  workflow_dispatch: {}
  schedule:
    # 2:30 AM UTC = 8:00 AM IST
    - cron: "30 2 * * *"

permissions:
  contents: write

jobs:
  Call-reusable-workflow:
    uses: UST-PACE/gh-actions-shared-library/.github/workflows/reusable_veracode_nightly_job_submit.yaml@main
    with:
      ref: ${{ github.ref }}
      branch: main
      build_options_file_name: build_options.txt
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
